name: bag-pipe
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - ipython
  - black
  - pytest
  - snakemake
  - click
  - hisat2
  - samtools
  - coreutils
  - pip
  - pip:
      - "read-break @ git+https://github.com/levycshl/read-break.git"
      - "bag-pipe @ git+https://github.com/levycshl/bag-pipe.git"
