name: bag_pipe
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - ipython
  - black
  - pytest
  - snakemake
  - pip
  - pip:
      - "read-break @ git+https://github.com/levycshl/read-break.git"
